version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: app/Dockerfile
    environment:
      - DEVICE=cpu
    volumes:
      - ./app/model:/app/model
    expose:
      - "8000"
    ports:
      - "8000:8000"

  nginx:
    image: nginx:alpine
    depends_on:
      - app
    ports:
      - "80:80"
    volumes:
      - ./app/nginx.conf:/etc/nginx/nginx.conf:ro
